apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "pg_dump-to-s3.fullname" . }}-s3
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: {{ include "pg_dump-to-s3.fullname" . }}-s3
    # this is how the Kind=Secret will look like
    {{- if eq .Values.s3 "EXO" }}
    template:
      type: Opaque
      data:
        configs3.conf: |
          [default]
          host_base = sos-{{ .Values.s3_zone }}.exo.io
          host_bucket = {{ .Values.host_bucket }}.sos-{{ .Values.s3_zone }}.exo.io
          access_key = {{"{{"}} .access_key | toString {{"}}"}}
          secret_key = {{"{{"}} .secret_key | toString {{"}}"}}
          use_https = True
    {{ end }}
    {{- if eq .Values.s3 "AWS" }}
    template:
      type: Opaque
      data:
        configs3.conf: |
          [default]
          host_base = s3.amazonaws.com
          host_bucket = {{ .Values.host_bucket }}.s3.amazonaws.com
          access_key = {{"{{"}} .access_key | toString {{"}}"}}
          secret_key =  {{"{{"}} .secret_key | toString {{"}}"}}
          use_https = True
    {{ end }}

  data:
  - secretKey: secret_key
    remoteRef:
      key: {{ .Values.s3_secret_path }}
      property: secret_key
  - secretKey: access_key
    remoteRef:
      key: {{ .Values.s3_secret_path }}
      property: access_key
