image:
  repository: ghcr.io/ducksify/pgdump-to-s3
  pullPolicy: Always

external-secrets:
  enabled: False

s3: EXO # EXO|AWS
s3_zone: eu-west-3 # only used by exoscale
host_base:  sos://backup-postgres
host_bucket:  sos://backup-postgres
db_secret_path: exoscale/postgres
s3_secret_path: exoscale/backups3